"""change type uuid

Revision ID: bb0a22c08e88
Revises: 7244611b608f
Create Date: 2022-03-30 00:57:34.918006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb0a22c08e88'
down_revision = '7244611b608f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_column('users', 'dd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dd', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
